project:
  type: website
  output-dir: _site
  resources:
    - bib/publications.bib
    - pdfs/**

website:
  title: "Sandeep M. Nayak, MD"
  site-url: https://smnayak1.github.io
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Publications
        href: publications.qmd
      - text: Teaching
        href: teaching.qmd
      - text: CV
        href: cv.qmd
    right:
      - icon: github
        href: https://github.com/smnayak1
      - text: Scholar
        href: "https://scholar.google.com/citations?user=qhEztHUAAAAJ&hl=en"
      - text: ORCID
        href: https://orcid.org/0000-0002-6832-0639
  page-footer:
    center: "© Sandeep M. Nayak"

format:
  html:
    theme: flatly
    toc: true
    number-sections: false
    smooth-scroll: true
    link-external-newwindow: true
    css: styles.css
    
metadata:
  markdown-in-bibliography: true
